<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <InternalsVisibleTo Include="D20Tek.Blazor.BrowserStorage.Tests" />
  </ItemGroup>

</Project>
